### ISSUE TITLE
不支持springboot集成的dubbo吗？

### ISSUE THREAD

**Issue by FeiLeMa** [Dromara/hmily#101]
按照指南接口引入了
`        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>hmily-annotation</artifactId>
            <version>2.0.5-RELEASE</version>
        </dependency>`
实现类
`        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>hmily-dubbo</artifactId>
            <version>2.0.5-RELEASE</version>
        </dependency>`
我用的是springboot的dubbo
`        
        <dependency>
            <groupId>com.alibaba.spring.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.0.0</version>
        </dependency>`

项目执行没有任何效果，只执行try。是不支持吗？

**Comment by yu199195** [comment]
应该是，他的服务不是spring的bean，支持xml
