### ISSUE TITLE
宕机情况下，cancel资源释放的问题

### ISSUE THREAD

**Issue by inseru** [Dromara/hmily#102]
问题：A服务调用B服务；B服务突然宕机，B服务的事务已经提交。但是由于连接中断，触发了A服务执行cancel逻辑；目前这种情况下，B服务的cancel逻辑不会被调用。

建议：能否增加一个逻辑，在cancel情况下，只要调用执行过远程的try阶段资源，就会触发对应cancel功能；由业务方去保证资源的幂等。

**Comment by yu199195** [comment]
现在就是这么样的，只要try调用成功，但是整个分布式事务失败，会调用cancel，如果try 阶段超时异常，本身会进行cancel。

**Comment by god8816** [comment]
> 现在就是这么样的，只要try调用成功，但是整个分布式事务失败，会调用cancel，如果try 阶段超时异常，本身会进行cancel。

B已经停机，事务已经提交，如果A cancel会导致数据不一致吧。

**Comment by yu199195** [comment]
b 宕机，还会提交事务？
