### ISSUE TITLE
No such bean name definition

### ISSUE THREAD

**Issue by CocoIceman** [Dromara/hmily#103]
场景1：正常执行业务，tcc-业务service的try和confirm阶段正常执行
场景2：异常事务使用DB存储，当定时任务recover异常事务retry时，会报错Spring上下文找不到service的bean
执行SpringBeanUtils.getInstance().getBean(MyServiceImpl.class);的 时候找不到bean。
按理说场景1中正常的话，bean是在容器中的，为什么场景2又找不到了

**Comment by CocoIceman** [comment]
我把源码拉下来，本地跑没这个问题，但是使用中央仓库的maven jar包就存在这个问题Hmily-SpringCloud

**Comment by yu199195** [comment]
你的服务必须是spring的bean

**Comment by CocoIceman** [comment]
不是这个问题

**Comment by wanggd2019** [comment]
我也遇到这个问题了，解决了吗，怎么解决
