### ISSUE TITLE
Spring Data JPA 可以用吗

### ISSUE THREAD

**Issue by ElanZh** [Dromara/hmily#105]
请问一下，这个框架实现了JTA吗？
如果我的项目使用springDataJPA可以使用吗？

**Comment by yu199195** [comment]
hmily是tcc模式，调用业务方法来进行回滚 和确认的，只要是spring 体系，都是可以的，和注册中心什么没关系

**Comment by ElanZh** [comment]
> 
> 
> hmily是tcc模式，调用业务方法来进行回滚 和确认的，只要是spring 体系，都是可以的，和注册中心什么没关系

我之前试过另外一个tcc框架，那个实现了JTA，结果我用springJPA死活集成不进去
