### ISSUE TITLE
使用redis存储时怎么设置database?

### ISSUE THREAD

**Issue by siaron** [Dromara/hmily#114]

**Comment by siaron** [comment]
`org.dromara.hmily.springcloud.loadbalancer.HmilyZoneAwareLoadBalancer `
这个自定义负载均衡有什么作用

**Comment by siaron** [comment]
`Set<byte[]> keys = jedisClient.keys((keyPrefix + "*").getBytes());` 这个keys 是不是可以优化下.

**Comment by yu199195** [comment]
看看前缀是啥，再说把

**Comment by siaron** [comment]
什么意思. 没有太明白, 是keys 命令吗? `redis.clients.jedis.BinaryJedis#keys` 看这个注释说的. 另外 redis 的 database 可以设置吗?
