### ISSUE TITLE
hmily spring cloud alibaba nacos

### ISSUE THREAD

**Issue by dengqiangloveju** [Dromara/hmily#119]
Field registration in org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration$ServiceRegistryEndpointConfiguration required a single bean, but 2 were found:
	- nacosRegistration: defined by method 'nacosRegistration' in class path resource [com/alibaba/cloud/nacos/NacosDiscoveryAutoConfiguration.class]
	- eurekaRegistration: defined in BeanDefinition defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration.class]

**Comment by dengqiangloveju** [comment]
hmily用nacos做服务发现报，难道hmily只支持eureka吗？

**Comment by yu199195** [comment]
支持nacos与spring cloud集成

**Comment by dengqiangloveju** [comment]
加入这个hmily的hmily-springcloud包会自动去走eureka注册。就会包上面的问题，这个应该没试过吧。

**Comment by yu199195** [comment]
你有啥好的建议吗
