### ISSUE TITLE
代码好像有点问题

### ISSUE THREAD

**Issue by lono2015** [Dromara/hmily#12]
public TccTransaction findById(String id) {
        try {

            final String redisKey = RepositoryPathUtils.buildRedisKey(keyPrefix, id);
            byte[] contents = jedisClient.get(redisKey.getBytes());
           //contents可能为空，好像代码中缺少判断
            if(contents == null) 
            	return null;
            return RepositoryConvertUtils.transformBean(contents, objectSerializer);
        } catch (Exception e) {
            throw new TccRuntimeException(e);
        }
    }

超时异常，库存数没有回滚

**Comment by yu199195** [comment]
超时异常，会要经过设置的时间之后，才会回滚

**Comment by lono2015** [comment]
我设置了回滚时间，有部分回滚，有些没有回滚，半个小时还是一样的，redis中存在回滚数据没有执行

在 2018-01-02 12:42:53，"流浪诗人丶" <notifications@github.com> 写道：


超时异常，会要经过设置的时间之后，才会回滚

**Comment by yu199195** [comment]
不会的  CoordinatorServiceImpl 类的 scheduledRollBack()   打个断点看下，超时异常，你是打了个断点，一直没释放？

**Comment by yu199195** [comment]
有模块异常，会调用cancel方法的
