### ISSUE TITLE
使用redis方式存储Hmily分布式事务日志

### ISSUE THREAD

**Issue by yu199195** [Dromara/hmily#139]
存储事务日志是SPI扩展。
实现项目在 hmily-repository-redis项目，完成实现 org.dromara.hmily.repository.reids.RedisRepository 类里面的方法就行。
目前已经实现 oracle，mysql，mongodb等存储，可以参考。难度不大。
有任何疑问可以找我沟通

**Comment by god8816** [comment]
认领这个需求
