### ISSUE TITLE
使用Zookeeper spi扩展方式实现Hmily日志存储

### ISSUE THREAD

**Issue by yu199195** [Dromara/hmily#140]
存储事务日志是SPI扩展。
实现项目在 hmily-repository-zookeeper项目，完成实现 org.dromara.hmily.repository.zookeeper.ZookeeperRepository 类里面的方法就行。
目前已经实现 oracle，mysql，mongodb等存储，可以参考。难度不大。

**Comment by cysy-lli** [comment]
报名

**Comment by cysy-lli** [comment]
认领
