### ISSUE TITLE
关于redis/zk实现的事务日志是否存在数据不一致？

### ISSUE THREAD

**Issue by vergilyn** [dromara/hmily#163]
```
public class HmilyTransaction {
    private Long transId;
    private List<HmilyParticipant> hmilyParticipants;
}

public class HmilyParticipant {
    private Long participantId;
    private Long transId;
    private Integer status;
}
```

根据以上定义，个人的理解是：类似于OneToMany的关系。
在redis-repository的实现中（zk类似）：
根据`createHmilyTransaction()`, 一个`HmilyTransaction`对象对应redis hash的一个元素，key = HMILY_TRANSACTION_GLOBAL，field = transId，value = HmilyTransaction。
根据`createHmilyParticipant()`, 一个`HmilyParticipant `对象也对应redis-hash的元素，key = HMILY_TRANSACTION_PARTICIPANT , field = participantId，value = HmilyParticipant。

之后`findByTransId(final Long transId)` 通过 HMILY_TRANSACTION_GLOBAL 获取 HmilyTransaction对象。
但是，存在方法`updateHmilyParticipantStatus(final Long participantId, final Integer status)`，该方法只update了 HMILY_TRANSACTION_PARTICIPANT 中的HmilyParticipant。**并未更新 HmilyTransaction 中包含的相同的 HmilyParticipant 对象**。

那么，针对**同一个participantId** 通过 GLOBAL 获取到的status 与 PARTICIPANT 中的状态是否会不一致？
这种数据不一致是否会造成影响？

**Comment by yu199195** [comment]
你觉得是 zk有问题，还是redis的， 这都是社区的人提供的，我没仔细去验证

**Comment by vergilyn** [comment]
> 你觉得是 zk有问题，还是redis的， 这都是社区的人提供的，我没仔细去验证
我觉得是实现代码的问题...😂 
 同一份数据 保存在了2处，更新却只更新了1处

**Comment by yu199195** [comment]
你可以提供pr来修复吗

**Comment by vergilyn** [comment]
> 你可以提供pr来修复吗

并不能~~ 最近沉迷找工作，无心写代码...

**Comment by yu199195** [comment]
>并未更新 HmilyTransaction 中包含的相同的 HmilyParticipant 对象。

我仔细看了一下，HmilyTransaction中的对象只是一个引用，它本身是不会保存 HmilyParticipant的，它的 HmilyParticipant 属性应该来自于其他查询
