### ISSUE TITLE
重试机制实现疑问

### ISSUE THREAD

**Issue by wenweihu86** [Dromara/hmily#17]
如果confirm阶段，部分下游成功，部分下游失败，这时为啥选择重试失败的，而不是回滚成功的？
比如库存场景，try阶段库存没问题，但在confirm阶段锁库存失败，因为被别的线程已经锁定成功了。

**Comment by yu199195** [comment]
到了confrim阶段的时候，证明所有的try 都已经执行完了， 如果confrim失败，继续执行confrim

**Comment by ZepPellN** [comment]
@yu199195 那某个下游一直confirm不成功，上游和其他confirm成功的下游并没有回滚，就导致不一致了吧
