### ISSUE TITLE
重构hmily-demo

### ISSUE THREAD

**Issue by yu199195** [dromara/hmily#172]
1.目前demo有 dubbo，motan，spring-cloud
每种rpc服务都是操作 订单，库存，账户 。 现在每种里面都有相同的数据库操作代码，
要把相同的代码抽离出来，共用

**Comment by bbaiggey** [comment]
assigned to me

**Comment by yu199195** [comment]
@bbaiggey  welcome，thanks

**Comment by archerForzmy** [comment]
I am looking forward to it

**Comment by yu199195** [comment]
@archerForzmy  hi， bbaiggey will do it， you can watch after he pr。
