### ISSUE TITLE
变量clazz命名导致代码歧义

### ISSUE THREAD

**Issue by photowey** [dromara/hmily#206]
0.版本号: 2.1.1
1.模块: hmily-spi
2.方法: org.dromara.hmily.spi.ExtensionLoader#loadClass
3.变量 284行: Class<?> clazz = Class.forName(className, true, loader);
3.1.变量 clazz 和 ExtensionLoader 的 变量 clazz(private final Class<T> clazz;) 重名
3.2.285行: if (!clazz.isAssignableFrom(clazz)) {} 会 被绕过
4.cast: 当285 被绕过后，会在 317 或者 319 行报:ClassCastException

**Comment by yu199195** [comment]
你可以提供一个pr，来修复它吗

**Comment by photowey** [comment]
认领
