### ISSUE TITLE
当SPI扩展没有被@HmilySPI 会触发ConcurrentHashMap#get 空指针

### ISSUE THREAD

**Issue by photowey** [dromara/hmily#207]
0.版本号: 2.1.1
1. 模块: hmily-spi
2. 方法: org.dromara.hmily.spi.ExtensionLoader#loadClass
3. 288行: String name = null;
4. 当扩展没有被@HmilySPI 修饰
4.1. HmilySPI hmilySPI = clazz.getAnnotation(HmilySPI.class);
4.2. 此时: 4.1 返回的结果为 null ,292 行 if test 结果为 false
4.3. 297行：设置到ExtensionEntity name == null, ExtensionEntity result = new ExtensionEntity(name, clazz, order, scope);
5. 192行: Holder<Object> holder = cachedInstances.get(entity.getName());
5.1.由于 步骤3 name == null, 故: entity.getName() == null
5.2.entity.getName() == null,会触发 cachedInstances.get 空指针

**Comment by yu199195** [comment]
必须要加注解的
