### ISSUE TITLE
hmily英文文档翻译

### ISSUE THREAD

**Issue by yu199195** [dromara/hmily#247]
这是Hmily目前的中文文档：https://gitee.com/shuaiqiyu/website/tree/master/docs/zh-cn/hmily
英语比较好的小伙伴可以参与进来一起将其翻译为英文。
这是Hmily的官网文档链接：https://dromara.org/website/zh-cn/docs/hmily/index.html

- 翻译任务一

- [x] Hmily的介绍

- [x] 分布式事务相关术语

- [x] 团队介绍

- [x] 常见问题FAQ

- 翻译任务二

- [x] 配置详解

- [x] 本地模式

- [x] Zookeeper配置中心

- [x] Nacos配置中心

- [x] Apollo配置中心

- [x] Etcd配置中心

- [x] Consul配置中心

- 翻译任务三

- [x] 注解详解

- [x] 事务上下文

- [x] Metrics信息

- [x] TCC模式

- [x] TAC模式

- 翻译任务四

- [x] 用户文档-Dubbo用户

- [x] 用户文档-Motan用户

- [x] 用户文档-Spring Cloud用户

- [x] 用户文档-Sofa-RPC用户

- [x] 用户文档-Tars用户

- [x] 用户文档-GRPC用户

- 翻译任务五

- [x] Dubbo快速体验

- [x] Motan快速体验

- [x] Spring Cloud快速体验

- [x] Sofa-RPC快速体验

- [x] Tars快速体验

- [x] GRPC快速体验

- 翻译任务六

- [x] 运维平台-启动admin

- [x] 贡献者指南

- [x] 提交者指南

- [x] 编码规范

- 翻译任务七

- [x]  项目的readme翻译

**Comment by yida-lxw** [comment]
well,leave it to me.

**Comment by 0x12FD16B** [comment]
1

**Comment by bigwillc** [comment]
2

**Comment by fightingting** [comment]
6

**Comment by yida-lxw** [comment]
The 4th is on me.

**Comment by nuo-promise** [comment]
The first one on me

**Comment by himalia6** [comment]
get 5

**Comment by wuudongdong** [comment]
get 6

**Comment by yida-lxw** [comment]
I go ahead to task 3.

**Comment by BestChong** [comment]
翻译

**Comment by BestChong** [comment]
get7

**Comment by Halcastle** [comment]
get8
