### ISSUE TITLE
请教：如何获取全局事务ID ？

### ISSUE THREAD

**Issue by small-rose** [dromara/hmily#248]
原来获取全局事务ID可以通过：
String localTradeNo = HmilyTransactionContextLocal.getInstance().get().getTransId();

请教一下新版的怎么获取呢，我使用

Long transId = HmilyTransactionHolder.getInstance().get().getTransId();

一直获取不到当前事务，请问是我是否使用错误？

官方文档 能否增加关于 版本更新 时一些注意事项呢

-----------------------
我暂时把获取全局ID注释了，又遇到了

 Error not found service provider for : org.dromara.hmily.core.service.HmilyTransactionHandlerFactory

一直无法解决，求指教

**Comment by yu199195** [comment]
这么应该是可以获取的，保证在一个线程里面
