### ISSUE TITLE
There is something wrong in the module hmily-demo-springcloud-order  resources

### ISSUE THREAD

**Issue by peiht** [dromara/hmily#262]
## Describe the bug

in the configraution file line 13, the default ip address is not right.

file path : hmily-demo/hmily-demo-springcloud/hmily-demo-springcloud-order/src/main/resources/application.yml

`url: jdbc:mysql://127.0.01:3306/hmily_order?useUnicode=true&characterEncoding=utf8
`

## Environment

- hmily version(s): [e.g. 2.1.2-SNAPSHOT]

## Expected behavior

should be `url: jdbc:mysql://127.0.0.1:3306/hmily_order?useUnicode=true&characterEncoding=utf8`

**Comment by peiht** [comment]
Can I submit a pull request to fix this?

**Comment by yu199195** [comment]
ok, you can fix it
