### ISSUE TITLE
关于一个服务调用两个接口的问题

### ISSUE THREAD

**Issue by wtjperi2003** [Dromara/hmily#29]
![qq 20180727163907](https://user-images.githubusercontent.com/10322892/43310976-b4f60dc4-91bb-11e8-9be9-02ea35567ba2.png)

**Comment by wtjperi2003** [comment]
我总结一下,如果a调用b和c服务,其中c服务的接口try方法抛异常,其对应的cancel不会执行,如果a调用了c里面的两个接口,后调用的接口try方法中抛异常,其对应的cancel会执行,但是先调用的接口对应的cancel方法不会执行,就在项目里的spring cloud demo里的inventory服务里多添加一个接口,order服务调用一下,就能测出来了

**Comment by siaron** [comment]
是的. 我也遇到了.
