### ISSUE TITLE
admin首页打不开

### ISSUE THREAD

**Issue by zhangzikai** [Dromara/hmily#30]
![image](https://user-images.githubusercontent.com/18569635/43337271-edf9e7ea-9205-11e8-8679-902e3ffb9ad0.png)
，项目牵出来后只改了数据库地址

**Comment by yu199195** [comment]
按照文档来~

**Comment by yu199195** [comment]
server:
   port: 8888
   context-path: /tcc-admin
   servlet:
     context-path: /tcc-admin

**Comment by kissss** [comment]
上次升级spring boot2.0之后 产生了不兼容的情况，已经提了修复，
