### ISSUE TITLE
TCC各阶段对应操作是否不合理？

### ISSUE THREAD

**Issue by xqxyxchy** [Dromara/hmily#35]
T-Try预留资源，demo中对应是锁库存、冻结资金；
C-Confirm确认执行业务，demo中是减库存、减资金--真正的业务方法（即添加TCC注解的方法才是业务）；
C-Cancel业务回滚，demo中是解锁库存、解冻资金；
---------------------------------------------------------------------------------------
但在框架中对应却不是这样的，真正的业务在框架处理时对应的是T-Try操作；
![hmily](https://user-images.githubusercontent.com/21134578/44762453-b1f7ce00-ab79-11e8-8ae5-10c26689bf87.png)
---------------------------------------------------------------------------------------
是我理解错误么？
求解惑。

**Comment by yu199195** [comment]
看代码，下面不是有confrim吗

**Comment by xqxyxchy** [comment]
我的疑惑不是有没有confirm。
而是真正的业务不是应该在confirm里面执行么？上面代码却是在try里面执行的。
是我理解错了，还是try和confirm可以反过来？try执行业务、confirm执行锁资源。

**Comment by jaychang9** [comment]
@xqxyxchy try阶段是判断资源是否可用，比如库存是否足量，余额是否足够，如果够的话，可以锁定资源。confirm阶段才是在业务上将锁定的资源真正扣减，cancel阶段是如果try阶段异常或超时，则将锁定的资源释放，返还到原资源库，比如库存或者余额
