### ISSUE TITLE
关于demo中库存量回滚

### ISSUE THREAD

**Issue by baihualinzi** [Dromara/hmily#49]
1.模拟下单付款操作在try阶段超时异常，此时账户系统和订单状态会回滚，但库存量不回滚，达到数据的一致性（异常指的是超时异常），这种情况下库存量不回滚了是因为库存量最终还是扣除了。
2.模拟下单付款操作在try阶段异常，此时账户系统和订单状态会回滚，但库存量回滚，达到数据的一致性（注意:这里模拟的是系统异常，或者rpc异常），这种情况是触发了本地数据库事务回滚，是这个原因么？谢谢！

**Comment by yu199195** [comment]
超时异常，依赖自身的事务日志进行回滚，根据你的配置来决定，多久来回滚，可以看定时回滚的服务：
ScheduledService

**Comment by baihualinzi** [comment]
我这边超时情况下：扣款放到freeze_amount中了，demo中account模块集成了hmily-tcc-spring-boot-starter-springcloud是不是就不用配置applicationContext.xml直接在yml配置就行了？我scheduledDelay : 128，为啥执行了三次128秒之后才执行取消付款接口而不是一次128秒后就立即回滚？我的retryMax :为30

**Comment by yu199195** [comment]
详情看源码，理解下吧
