### ISSUE TITLE
需要哪些工具

### ISSUE THREAD

**Issue by ChristianWyc** [Dromara/hmily#5]
需要哪里开发工具

**Comment by yu199195** [comment]
啥意思？

**Comment by ChristianWyc** [comment]
就是除了jdk1.8之外需要哪些基本的配置才可以把代码fork下来能运行

**Comment by yu199195** [comment]
jdk1.8 就行，其他的不需要。 一些redis，zookeeper还是要有的

**Comment by ChristianWyc** [comment]
有没有这个安装配置手册呀

**Comment by yu199195** [comment]
朋友，你的rpc 框架如果是dubbo，那么zookeeper之类的是需要的啊，如果是springcloud，就只需要jdk8

**Comment by ChristianWyc** [comment]
兄弟，如果我的框架是springcloud，是不是直接fork下来，改一下数据库连接就可以运行了

**Comment by yu199195** [comment]
是的，按照文档上走就行了

**Comment by ChristianWyc** [comment]
什么文档

**Comment by ChristianWyc** [comment]
兄弟文档在哪里，指教
