### ISSUE TITLE
我测试了一下，并发100，压测了300w数据，发现：异步的confirm和cancel处理的非常慢！而且还有数据不一致的情况

### ISSUE THREAD

**Issue by AresKingCarry** [Dromara/hmily#51]
压测报告：
![image](https://user-images.githubusercontent.com/25707053/47422339-f63bcf00-d7b4-11e8-8f6e-9394f9fbfcba.png)

压测中，发现数据不一致，库存和账户对应不上，不知道为什么有的方法就直接调用cancel了，帮忙解答一下，最近选tcc框架，谢谢。

**Comment by yu199195** [comment]
你压测的是什么？ 直接调用cancel肯定是你的服务try阶段有异常了呗，你自身的方法执行慢，和框架有啥关系？ 你不加分布式事务，你就直接调用，压测试试？

**Comment by AresKingCarry** [comment]
怎么提高异步执行的速度？

**Comment by harvies** [comment]
> 压测报告：
> ![image](https://user-images.githubusercontent.com/25707053/47422339-f63bcf00-d7b4-11e8-8f6e-9394f9fbfcba.png)
> 
> 压测中，发现数据不一致，库存和账户对应不上，不知道为什么有的方法就直接调用cancel了，帮忙解答一下，最近选tcc框架，谢谢。

![qq 20181027130449](https://user-images.githubusercontent.com/16585330/47599827-f8866f00-d9e8-11e8-8f30-25b5933a7ed5.png)
![qq 20181027130503](https://user-images.githubusercontent.com/16585330/47599828-fde3b980-d9e8-11e8-9f61-8086bfcec773.png)
demo更新账户余额sql不是原子的(freeze_amount字段被别的线程修改了，导致freeze_amount成负的了)

**Comment by harvies** [comment]
> @harvies master分支吗，可以提供pr

是的,master分支,最近我把spring cloud demo扣款优化下,发个pr
