### ISSUE TITLE
请问支持spring4吗，demo用的是spring5

### ISSUE THREAD

**Issue by shenzhanwang** [Dromara/hmily#52]
请问支持spring4吗，demo用的是spring5。用spring4会报错.

**Comment by shenzhanwang** [comment]
报错：java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector

**Comment by yu199195** [comment]
和spring的版本没关系，这个是你的包有冲突了，或者少包，解决就可以

**Comment by shenzhanwang** [comment]
缺的这个包确实是来自spring5的。
