### ISSUE TITLE
关于服务分布式部署后事物回滚的问题

### ISSUE THREAD

**Issue by jinshubao** [Dromara/hmily#58]
目前看代码结构，于每个依赖tcc的项目都会引入hmily-core包，该包中的回滚定时任务一直在执行。

我有个疑惑
假设：账户服务分布式部署（account-service-a,account-service-b），发起了一笔交易并且账户服务产生了异常。那么，两个账户服务是否会分别发起一次回滚请求，也就相当于发起两次回滚请求？

**Comment by q920447939** [comment]
这个应该自己做分布式事务幂等性

**Comment by q920447939** [comment]
> 目前看代码结构，于每个依赖tcc的项目都会引入hmily-core包，该包中的回滚定时任务一直在执行。
> 
> 我有个疑惑
> 假设：账户服务分布式部署（account-service-a,account-service-b），发起了一笔交易并且账户服务产生了异常。那么，两个账户服务是否会分别发起一次回滚请求，也就相当于发起两次回滚请求？

这个应该自己做分布式事务幂等性

**Comment by yu199195** [comment]
定时任务只是在你服务down机情况下，才会执行.  其他的rpc异常，不会执行的，框架保证了只执行一次，不过最后自己做下幂等。

**Comment by yu199195** [comment]
集群部署的时候，定时任务，会有个version字段，只有更新成功的才执行，而且 基本上不是通过定时任务来回滚的，。。。

**Comment by jinshubao** [comment]
大概了解了过程，谢谢你的回复

发自我的 iPhone
