### ISSUE TITLE
执行confirm反射方法时，用@Reference注解的bean找不到

### ISSUE THREAD

**Issue by xyzhimo** [Dromara/hmily#59]
![image](https://user-images.githubusercontent.com/18374795/48895654-90f4ff80-ee80-11e8-824b-452b9bebe984.png)
执行反射方法调用时，用@Reference注解的Provider不能本地调用
![image](https://user-images.githubusercontent.com/18374795/48895795-e9c49800-ee80-11e8-912e-6cfbd09c7e87.png)

**Comment by yu199195** [comment]
没在spring 容器中？

**Comment by justxiaoyizhi** [comment]
嗯，dubbo用@Reference注解是没在Spring容器中的，但是demo上，用的xml注解，是可以加载到Spring容器中

**Comment by xyzhimo** [comment]
> 没在spring 容器中？

`public void init() {
        Collection<ReferenceBean<?>> referenceBeans = this.referenceAnnotationBeanPostProcessor.getReferenceBeans();
        for (ReferenceBean<?> referenceBean : referenceBeans) {
            try {
                SpringBeanUtils.getInstance()
                        .registerBean(referenceBean.getObjectType().getName(), referenceBean.getObject());
            } catch (Exception e) {
                e.printStackTrace();
                log.warn("dubbo @reference bean inject spring container meet exception, objectType:{}", e,
                        referenceBean.getObjectType());
            }
        }
    }`
插入这段代码，解决@reference注解没有加载到spring容器中是否可以？

**Comment by yu199195** [comment]
@xyzhimo  你的这段代码，是写在哪里的？

**Comment by yu199195** [comment]
下个版本解决。。。
