### ISSUE TITLE
有病毒

### ISSUE THREAD

**Issue by crazyhuntsman** [Dromara/hmily#6]
下载后提示有病毒

^_^!!!!

**Comment by yu199195** [comment]
不会吧

**Comment by crazyhuntsman** [comment]
IE下载OK。。。。现在准备转成JDK7。。。^_^!。。还是建议向下兼容，必竟很多系统还是低版本的JDK

**Comment by yu199195** [comment]
JDK 7不行，我在项目里大量使用了lambda表达式，等函数式编程，等jdk8的新特性

**Comment by crazyhuntsman** [comment]
@yu199195 嗯。所以我全部都改到1.7兼容了。试跑OK通过。
