### ISSUE TITLE
库存回滚异常

### ISSUE THREAD

**Issue by WuZhiCheng** [Dromara/hmily#67]
库存里写了个异常，没有调用cancelMethod是什么原因
![image](https://user-images.githubusercontent.com/10386961/50078135-1d48d700-0221-11e9-8d1c-e71147fc1b1b.png)

**Comment by yu199195** [comment]
自身的异常异常不会执行cancel，而是其他的服务cancel，自身请使用本地事务

**Comment by WuZhiCheng** [comment]
就是说如果我希望本地事务回滚的话，需要使用 @Transactional？
![image](https://user-images.githubusercontent.com/10386961/50125946-dea93000-02a5-11e9-824c-26fdc7f93554.png)

**Comment by yu199195** [comment]
是的。你可以不用分布式事务，不加Transaction注解，试下，它会不会插入进去。他自己异常，其他节点进行回滚，后续可以考虑把当年节点也加入进来，进行回滚

**Comment by yu199195** [comment]
但是你要考虑一个问题，如果是超时异常怎么处理，需要回滚吗，回滚方法 和try方法的执行顺序问题？

**Comment by WuZhiCheng** [comment]
好的  谢谢

**Comment by tlhhup** [comment]
你这个问题处理了嘛？本地事务可以回滚吗？
