### ISSUE TITLE
hmily的SpringBeanUtils获取bean报空

### ISSUE THREAD

**Issue by Avengervick** [Dromara/hmily#70]
![1545214283 1](https://user-images.githubusercontent.com/18612691/50214388-2c638c80-03bb-11e9-8be6-11a498cad22a.png)

**Comment by yu199195** [comment]
参考文档来，

**Comment by zzyymaggie** [comment]
我也遇到这个问题了，我发现是因为hmily-demo-springcloud-order这个工程的依赖包问题。依赖hmily-spring-boot-starter-springcloud就会报这个错，而你依赖的是这个包
```
 <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>hmily-springcloud</artifactId>
        </dependency>
```

**Comment by dengqiangloveju** [comment]
想问下大哥们这个是什么个意思？我也遇到了，是不是主事务不能用hmily-spring-boot-starter-springcloud？
