### ISSUE TITLE
集群模式下定时恢复问题

### ISSUE THREAD

**Issue by SpecialYang** [Dromara/hmily#71]
这里假设是发起者发起重试confirm，此时我有发起者的集群，这时他们都会去发起重试，虽然代码里有乐观锁机制保证了最大重试次数，但是如果机器A修改retrycount后，发起confirm，机器B仅跟着修改retrycount，发起confirm。  
若业务没有幂等处理，这样就会导致confirm执行两次，所以需要用户保证业务的confirm和cancel的幂等吧？

**Comment by yu199195** [comment]
首先定时恢复，在发起者一方，是有很严格的限制，如果是集群不会发生。除非整个集群挂掉。你说的情况，不会有，首先要理解整个框架，而不是去意淫。。。

**Comment by SpecialYy** [comment]
整体代码我看了啊，可能我没有描述清楚。假设有集群发起者（2个， A 和 B），用户调用了A机器开始的分布式事务，假设confirm阶段出错了。机器A和B（都为发起者）通过定时任务都可以扫描到这个事务，然后开始重试，这时就会导致confirm执行两次吧，我没有看到加锁。仅由乐观锁保证了重试次数的正确性

**Comment by SpecialYy** [comment]
我感觉我没理解错啊，反复看了好多遍，哎

**Comment by hhanhao** [comment]
楼主说的有道理

**Comment by HendSame** [comment]
我也觉得有这个问题，支持楼主
