### ISSUE TITLE
Consider defining a bean of type 'org.dromara.hmily.core.service.HmilyApplicationService' in your configuration.

### ISSUE THREAD

**Issue by dante7qx** [Dromara/hmily#81]
添加依赖
<dependency>
			<groupId>org.dromara</groupId>
			<artifactId>hmily-spring-boot-starter-parent</artifactId>
</dependency>

程序启动报错

Parameter 0 of constructor in org.dromara.hmily.core.coordinator.impl.HmilyCoordinatorServiceImpl required a bean of type 'org.dromara.hmily.core.service.HmilyApplicationService' that could not be found.

**Comment by yu199195** [comment]
依赖添加错误，请看文档
