### ISSUE TITLE
你好咨询个问题，hmily和springcloud使用的注册中心组件有关系吗

### ISSUE THREAD

**Issue by zjypp** [Dromara/hmily#83]
你好咨询个问题，hmily和springcloud使用的注册中心组件有关系吗
如果springcloud我使用Consul做注册中心，不使用Eurkea，会不会有问题

另外一个问题hmily使用的是哪个日志依赖，和springboot中默认的有冲突

**Comment by zjypp** [comment]
排除了一个日志依赖解决了上个问题，又出来一个新问题：

Field payServiceClient in com.zjy.cld2019.orderservice.controller.OrderController required a single bean, but 2 were found:
	- feignBuilder: defined by method 'feignBuilder' in class path resource [org/dromara/hmily/springcloud/feign/HmilyRestTemplateConfiguration.class]
	- feignHystrixBuilder: defined by method 'feignHystrixBuilder' in class path resource [org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignClientAutoConfiguration.class]

**Comment by yu199195** [comment]
使用最新的版本，日志使用的logBack

**Comment by yu199195** [comment]
hmily 和springcloud的版本 关系不大
