### ISSUE TITLE
这个try 阶段，接口提供方超时，但执行成功了。这种怎么处理啊？

### ISSUE THREAD

**Issue by csy512889371** [Dromara/hmily#90]
问个问题。paymentService.makePayment 方法中，调用inventoryClient.decrease。在decrease方法中让其锁定库存成功，但段点超时。 这种情况订单回归了，库存锁定的没发回滚。

**Comment by yu199195** [comment]
库存依赖自身的定时任务进行回滚，断点超时，或者其他超时，对调用着来说是异常的，对本身来说不确定是否成功，如果成功，那么就自身回滚，如果不成功，那就什么都不做

**Comment by csy512889371** [comment]
如果成功，那么就自身回滚? 这种情况使用定时任务回滚吗？我看hmily_order_service 中记录的事务已经被删除了。那么定时任务回滚没有依据了不知道将 inventory 表中多少的lock_inventory回滚。

**Comment by yu199195** [comment]
说了库存自己回滚，和order有啥关系？

**Comment by csy512889371** [comment]
确实，我理解错了，每个微服务都会有个事务日志表，库存的回滚日志 通过 hmily_inventory_service来实现。谢谢啊，理解了。 recoverDelayTime 这个 时间设置是不是必须大于实际接口执行时间？ 设置小于库存接口执行超时时间 会不会有问题？

**Comment by yu199195** [comment]
看你的设置。。
