### ISSUE TITLE
分布式事务调度之间有依赖关系如何完成 try 逻辑？

### ISSUE THREAD

**Issue by abbish** [Dromara/hmily#91]
咨询个 TCC 在服务间有依赖关系的处理情景思路

比如说 M 作为事务发起，需要顺序调用 A，B，C，调用 B 的时候需要依赖 A 的返回结果，这时候
在做 A，B，C 的 try 时处理思路是怎样的？

谢谢

**Comment by yu199195** [comment]
也是一样的，只要在一个切面里面，一个发起的方法里面完成就可以
